[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m pip install --upgrade pip setuptools>=50.0.0 wheel",
    "python -m pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "gunicorn --bind=0.0.0.0:$PORT --workers=2 --worker-class=sync --worker-connections=1000 --max-requests=1000 --max-requests-jitter=100 --preload --timeout=30 main:app"