[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = [
    "python311", 
    "python311Packages.pip",
    "gcc",
    "glib",
    "libGL",
    "libgcc",
    "glibc",
    "stdenv.cc.cc.lib",
    "libstdcxx5",
    "opencv4",
    "pkg-config"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn --bind=0.0.0.0:$PORT --workers=2 --timeout=30 main:app"